<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'csa_guzzle.cache.adapter.doctrine' shared service.

return $this->services['csa_guzzle.cache.adapter.doctrine'] = new \Csa\Bundle\GuzzleBundle\GuzzleHttp\Cache\DoctrineAdapter();
