<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'csa_guzzle.cache_warmer.description' shared service.

return $this->services['csa_guzzle.cache_warmer.description'] = new \Csa\Bundle\GuzzleBundle\Description\CacheWarmer\DescriptionCacheWarmer(${($_ = isset($this->services['csa_guzzle.description_factory']) ? $this->services['csa_guzzle.description_factory'] : $this->load('getCsaGuzzle_DescriptionFactoryService.php')) && false ?: '_'});
