<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'csa_guzzle.description_factory' shared service.

return $this->services['csa_guzzle.description_factory'] = new \Csa\Bundle\GuzzleBundle\Factory\DescriptionFactory(${($_ = isset($this->services['csa_guzzle.description_loader']) ? $this->services['csa_guzzle.description_loader'] : $this->load('getCsaGuzzle_DescriptionLoaderService.php')) && false ?: '_'}, $this->targetDirs[0], true);
