<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'csa_guzzle.description_loader.resolver' shared service.

return $this->services['csa_guzzle.description_loader.resolver'] = new \Symfony\Component\Config\Loader\LoaderResolver([0 => new \Csa\Bundle\GuzzleBundle\Description\Loader\JsonLoader()]);
