<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.design.theme.page_layouts_customization' shared service.

return $this->services['form.type.design.theme.page_layouts_customization'] = new \PrestaShopBundle\Form\Admin\Improve\Design\Theme\PageLayoutsCustomizationType(${($_ = isset($this->services['prestashop.core.form.choice_provider.theme_page_layouts']) ? $this->services['prestashop.core.form.choice_provider.theme_page_layouts'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_ThemePageLayoutsService.php')) && false ?: '_'}->getChoices());
