<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.international.tax_options' shared service.

return $this->services['form.type.international.tax_options'] = new \PrestaShopBundle\Form\Admin\Improve\International\Tax\TaxOptionsType(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}->getBoolean("PS_USE_ECOTAX"), ${($_ = isset($this->services['prestashop.core.form.choice_provider.tax_address_type_choice_provider']) ? $this->services['prestashop.core.form.choice_provider.tax_address_type_choice_provider'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_TaxAddressTypeChoiceProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.form.choice_provider.tax_rule_group_choice_provider']) ? $this->services['prestashop.core.form.choice_provider.tax_rule_group_choice_provider'] : ($this->services['prestashop.core.form.choice_provider.tax_rule_group_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\TaxRuleGroupChoiceProvider())) && false ?: '_'});
