<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.customer.required_fields' shared service.

return $this->services['form.type.customer.required_fields'] = new \PrestaShopBundle\Form\Admin\Sell\Customer\RequiredFieldsType(${($_ = isset($this->services['prestashop.core.form.choice_provider.customer_required_fields']) ? $this->services['prestashop.core.form.choice_provider.customer_required_fields'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_CustomerRequiredFieldsService.php')) && false ?: '_'}->getChoices());
