<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.cms_page' shared service.

return $this->services['form.type.cms_page'] = new \PrestaShopBundle\Form\Admin\Improve\Design\Pages\CmsPageType(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.core.form.choice_provider.cms_categories']) ? $this->services['prestashop.core.form.choice_provider.cms_categories'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_CmsCategoriesService.php')) && false ?: '_'}->getChoices(), ${($_ = isset($this->services['prestashop.adapter.multistore_feature']) ? $this->services['prestashop.adapter.multistore_feature'] : $this->load('getPrestashop_Adapter_MultistoreFeatureService.php')) && false ?: '_'}->isUsed());
