<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.webservice.webservice_key_type' shared service.

$this->services['form.type.webservice.webservice_key_type'] = $instance = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Webservice\WebserviceKeyType(${($_ = isset($this->services['prestashop.adapter.multistore_feature']) ? $this->services['prestashop.adapter.multistore_feature'] : $this->load('getPrestashop_Adapter_MultistoreFeatureService.php')) && false ?: '_'}->isUsed(), ${($_ = isset($this->services['prestashop.adapter.form.choice_provider.resources_choice_provider']) ? $this->services['prestashop.adapter.form.choice_provider.resources_choice_provider'] : ($this->services['prestashop.adapter.form.choice_provider.resources_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ResourcesChoiceProvider())) && false ?: '_'}->getChoices(), ${($_ = isset($this->services['prestashop.core.form.choice_provider.permissions_choice_provider']) ? $this->services['prestashop.core.form.choice_provider.permissions_choice_provider'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_PermissionsChoiceProviderService.php')) && false ?: '_'}->getChoices());

$instance->setTranslator(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});

return $instance;
