<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.import.import_data_configuration' shared service.

return $this->services['form.type.import.import_data_configuration'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Import\ImportDataConfigurationType(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.core.form.choice_provider.import_match_configuration']) ? $this->services['prestashop.core.form.choice_provider.import_match_configuration'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_ImportMatchConfigurationService.php')) && false ?: '_'}->getChoices(), ${($_ = isset($this->services['prestashop.core.form.choice_provider.import_entity_field']) ? $this->services['prestashop.core.form.choice_provider.import_entity_field'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_ImportEntityFieldService.php')) && false ?: '_'}->getChoices());
