<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.translations.add_update_language' shared service.

return $this->services['form.type.translations.add_update_language'] = new \PrestaShopBundle\Form\Admin\Improve\International\Translations\AddUpdateLanguageType(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.core.form.choice_provider.non_installed_localization']) ? $this->services['prestashop.core.form.choice_provider.non_installed_localization'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_NonInstalledLocalizationService.php')) && false ?: '_'}->getChoices());
