<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.localization.generate_mails' shared service.

return $this->services['form.type.localization.generate_mails'] = new \PrestaShopBundle\Form\Admin\Improve\Design\MailTheme\GenerateMailsType(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.core.form.choice_provider.mail_themes']) ? $this->services['prestashop.core.form.choice_provider.mail_themes'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_MailThemesService.php')) && false ?: '_'}->getChoices(), ${($_ = isset($this->services['prestashop.core.form.choice_provider.theme_by_name_with_emails']) ? $this->services['prestashop.core.form.choice_provider.theme_by_name_with_emails'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_ThemeByNameWithEmailsService.php')) && false ?: '_'}->getChoices());
