<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.order_preferences.general' shared service.

return $this->services['form.type.order_preferences.general'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\OrderPreferences\GeneralType(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.adapter.data_provider.currency']) ? $this->services['prestashop.adapter.data_provider.currency'] : $this->getPrestashop_Adapter_DataProvider_CurrencyService()) && false ?: '_'}->getDefaultCurrencyIsoCode(), ${($_ = isset($this->services['prestashop.adapter.data_provider.cms']) ? $this->services['prestashop.adapter.data_provider.cms'] : ($this->services['prestashop.adapter.data_provider.cms'] = new \PrestaShop\PrestaShop\Adapter\CMS\CMSDataProvider())) && false ?: '_'}->getCmsChoices());
