<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.common.team.profile_choice' shared service.

return $this->services['form.type.common.team.profile_choice'] = new \PrestaShopBundle\Form\Admin\Type\Common\Team\ProfileChoiceType(${($_ = isset($this->services['prestashop.adapter.form.choice_provider.profile_by_id_choice_provider']) ? $this->services['prestashop.adapter.form.choice_provider.profile_by_id_choice_provider'] : $this->load('getPrestashop_Adapter_Form_ChoiceProvider_ProfileByIdChoiceProviderService.php')) && false ?: '_'}->getChoices());
