<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.performance.smarty' shared service.

return $this->services['form.type.performance.smarty'] = new \PrestaShopBundle\Form\Admin\AdvancedParameters\Performance\SmartyType();
