<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.performance.ccc' shared service.

return $this->services['form.type.performance.ccc'] = new \PrestaShopBundle\Form\Admin\AdvancedParameters\Performance\CombineCompressCacheType();
