<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.order.invoices.invoice_options' shared service.

return $this->services['form.type.order.invoices.invoice_options'] = new \PrestaShopBundle\Form\Admin\Sell\Order\Invoices\InvoiceOptionsType(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.core.form.choice_provider.invoice_model_by_name']) ? $this->services['prestashop.core.form.choice_provider.invoice_model_by_name'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_InvoiceModelByNameService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.data_provider.order_invoice']) ? $this->services['prestashop.adapter.data_provider.order_invoice'] : ($this->services['prestashop.adapter.data_provider.order_invoice'] = new \PrestaShop\PrestaShop\Adapter\Invoice\OrderInvoiceDataProvider())) && false ?: '_'}->getNextInvoiceNumber());
