<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.common.category_choice_tree' shared service.

return $this->services['form.type.common.category_choice_tree'] = new \PrestaShopBundle\Form\Admin\Type\CategoryChoiceTreeType(${($_ = isset($this->services['prestashop.adapter.form.choice_provider.category_tree_choice_provider']) ? $this->services['prestashop.adapter.form.choice_provider.category_tree_choice_provider'] : $this->load('getPrestashop_Adapter_Form_ChoiceProvider_CategoryTreeChoiceProviderService.php')) && false ?: '_'}->getChoices());
