<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.order.invoices.generate_by_status' shared service.

return $this->services['form.type.order.invoices.generate_by_status'] = new \PrestaShopBundle\Form\Admin\Sell\Order\Invoices\GenerateByStatusType(${($_ = isset($this->services['prestashop.core.form.choice_provider.order_state_by_id']) ? $this->services['prestashop.core.form.choice_provider.order_state_by_id'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_OrderStateByIdService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.api.order_invoice.repository']) ? $this->services['prestashop.core.api.order_invoice.repository'] : $this->load('getPrestashop_Core_Api_OrderInvoice_RepositoryService.php')) && false ?: '_'}->countByOrderState(${($_ = isset($this->services['prestashop.adapter.shop.context']) ? $this->services['prestashop.adapter.shop.context'] : ($this->services['prestashop.adapter.shop.context'] = new \PrestaShop\PrestaShop\Adapter\Shop\Context())) && false ?: '_'}->getContextListShopID()));
