<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.customer.delete_customer' shared service.

return $this->services['form.type.customer.delete_customer'] = new \PrestaShopBundle\Form\Admin\Sell\Customer\DeleteCustomersType(${($_ = isset($this->services['prestashop.core.form.choice_provider.customer_delete_method']) ? $this->services['prestashop.core.form.choice_provider.customer_delete_method'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_CustomerDeleteMethodService.php')) && false ?: '_'}->getChoices());
