<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.extension.money' shared service.

return $this->services['form.type.extension.money'] = new \PrestaShopBundle\Form\Admin\Type\CustomMoneyType();
