<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.cms_page_category' shared service.

$this->services['form.type.cms_page_category'] = $instance = new \PrestaShopBundle\Form\Admin\Improve\Design\Pages\CmsPageCategoryType(${($_ = isset($this->services['prestashop.core.form.choice_provider.cms_categories']) ? $this->services['prestashop.core.form.choice_provider.cms_categories'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_CmsCategoriesService.php')) && false ?: '_'}->getChoices(), ${($_ = isset($this->services['prestashop.adapter.multistore_feature']) ? $this->services['prestashop.adapter.multistore_feature'] : $this->load('getPrestashop_Adapter_MultistoreFeatureService.php')) && false ?: '_'}->isUsed());

$instance->setTranslator(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});

return $instance;
