<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.shipping_preferences.carrier_options' shared service.

return $this->services['form.type.shipping_preferences.carrier_options'] = new \PrestaShopBundle\Form\Admin\Improve\Shipping\Preferences\CarrierOptionsType(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.adapter.data_provider.carrier']) ? $this->services['prestashop.adapter.data_provider.carrier'] : $this->load('getPrestashop_Adapter_DataProvider_CarrierService.php')) && false ?: '_'}->getActiveCarriersChoices(), ${($_ = isset($this->services['prestashop.adapter.data_provider.carrier']) ? $this->services['prestashop.adapter.data_provider.carrier'] : $this->load('getPrestashop_Adapter_DataProvider_CarrierService.php')) && false ?: '_'}->getOrderByChoices(), ${($_ = isset($this->services['prestashop.adapter.data_provider.carrier']) ? $this->services['prestashop.adapter.data_provider.carrier'] : $this->load('getPrestashop_Adapter_DataProvider_CarrierService.php')) && false ?: '_'}->getOrderWayChoices());
