<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.recommendedmodules.presenter' shared service.

return $this->services['mbo.recommendedmodules.presenter'] = new \PrestaShop\Module\Mbo\RecommendedModule\RecommendedModulePresenter();
