<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.tab.collection.provider' shared service.

return $this->services['mbo.tab.collection.provider'] = new \PrestaShop\Module\Mbo\Tab\TabCollectionProvider(${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}, ${($_ = isset($this->services['mbo.externalcontent.provider']) ? $this->services['mbo.externalcontent.provider'] : ($this->services['mbo.externalcontent.provider'] = new \PrestaShop\Module\Mbo\ExternalContentProvider\ExternalContentProvider())) && false ?: '_'}, ${($_ = isset($this->services['mbo.tab.collection.factory']) ? $this->services['mbo.tab.collection.factory'] : $this->load('getMbo_Tab_Collection_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.cache.provider']) ? $this->services['doctrine.cache.provider'] : ($this->services['doctrine.cache.provider'] = new \Doctrine\Common\Cache\FilesystemCache(($this->targetDirs[0].'/doctrine')))) && false ?: '_'});
