<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.tab.collection.factory' shared service.

return $this->services['mbo.tab.collection.factory'] = new \PrestaShop\Module\Mbo\Tab\TabCollectionFactory(${($_ = isset($this->services['mbo.adapter.module_collection_data_provider']) ? $this->services['mbo.adapter.module_collection_data_provider'] : $this->load('getMbo_Adapter_ModuleCollectionDataProviderService.php')) && false ?: '_'});
