<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.controller.themes.catalog' shared service.

return $this->services['mbo.controller.themes.catalog'] = new \PrestaShop\Module\Mbo\Controller\Admin\ThemeCatalogController(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'}, ${($_ = isset($this->services['mbo.externalcontent.provider']) ? $this->services['mbo.externalcontent.provider'] : ($this->services['mbo.externalcontent.provider'] = new \PrestaShop\Module\Mbo\ExternalContentProvider\ExternalContentProvider())) && false ?: '_'}, ${($_ = isset($this->services['mbo.addons_selection_link_provider']) ? $this->services['mbo.addons_selection_link_provider'] : $this->load('getMbo_AddonsSelectionLinkProviderService.php')) && false ?: '_'});
