<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.delivery.slip.pdf.form_handler' shared service.

return $this->services['prestashop.adapter.order.delivery.slip.pdf.form_handler'] = new \PrestaShop\PrestaShop\Core\Form\FormHandler(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}->createBuilder(), ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.order.delivery.slip.pdf.form_provider']) ? $this->services['prestashop.adapter.order.delivery.slip.pdf.form_provider'] : $this->load('getPrestashop_Adapter_Order_Delivery_Slip_Pdf_FormProviderService.php')) && false ?: '_'}, ['pdf' => 'PrestaShopBundle\\Form\\Admin\\Sell\\Order\\Delivery\\SlipPdfType'], 'OrderDeliverySlipPdf', 'slip_pdf_form');
