<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.translation.extractor.smarty' shared service.

return $this->services['prestashop.translation.extractor.smarty'] = new \PrestaShop\TranslationToolsBundle\Translation\Extractor\SmartyExtractor(${($_ = isset($this->services['prestashop.compiler.smarty.template']) ? $this->services['prestashop.compiler.smarty.template'] : $this->load('getPrestashop_Compiler_Smarty_TemplateService.php')) && false ?: '_'});
