<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.mail_template.twig_renderer' shared service.

$this->services['prestashop.adapter.mail_template.twig_renderer'] = $instance = new \PrestaShop\PrestaShop\Adapter\MailTemplate\MailTemplateTwigRenderer(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.mail_template.variables_builder']) ? $this->services['prestashop.core.mail_template.variables_builder'] : $this->load('getPrestashop_Core_MailTemplate_VariablesBuilderService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'});

$instance->addTransformation(${($_ = isset($this->services['prestashop.core.mail_template.transformation.css_inline']) ? $this->services['prestashop.core.mail_template.transformation.css_inline'] : ($this->services['prestashop.core.mail_template.transformation.css_inline'] = new \PrestaShop\PrestaShop\Core\MailTemplate\Transformation\CSSInlineTransformation())) && false ?: '_'});
$instance->addTransformation(${($_ = isset($this->services['prestashop.core.mail_template.transformation.html_textify']) ? $this->services['prestashop.core.mail_template.transformation.html_textify'] : ($this->services['prestashop.core.mail_template.transformation.html_textify'] = new \PrestaShop\PrestaShop\Core\MailTemplate\Transformation\HTMLToTextTransformation())) && false ?: '_'});

return $instance;
