<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.profile.command_handler.bulk_delete_profile' shared service.

return $this->services['prestashop.adapter.profile.command_handler.bulk_delete_profile'] = new \PrestaShop\PrestaShop\Adapter\Profile\CommandHandler\BulkDeleteProfileHandler(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}->get("_PS_ADMIN_PROFILE_"), ${($_ = isset($this->services['prestashop.adapter.data_provider.employee']) ? $this->services['prestashop.adapter.data_provider.employee'] : $this->load('getPrestashop_Adapter_DataProvider_EmployeeService.php')) && false ?: '_'});
