<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.contact.deleter' shared service.

return $this->services['prestashop.adapter.contact.deleter'] = new \PrestaShop\PrestaShop\Adapter\Support\ContactDeleter();
