<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.shop.command_handler.upload_logos_handler' shared service.

return $this->services['prestashop.adapter.shop.command_handler.upload_logos_handler'] = new \PrestaShop\PrestaShop\Adapter\Shop\CommandHandler\UploadLogosHandler(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.shop.logo_uploader']) ? $this->services['prestashop.core.shop.logo_uploader'] : $this->load('getPrestashop_Core_Shop_LogoUploaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'});
