<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.import.factory.data_row.collection_factory' shared service.

return $this->services['prestashop.core.import.factory.data_row.collection_factory'] = new \PrestaShop\PrestaShop\Core\Import\File\DataRow\Factory\DataRowCollectionFactory(${($_ = isset($this->services['prestashop.core.import.csv_file_reader']) ? $this->services['prestashop.core.import.csv_file_reader'] : $this->load('getPrestashop_Core_Import_CsvFileReaderService.php')) && false ?: '_'});
