<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.supplier.provider.supplier_address' shared service.

return $this->services['prestashop.adapter.supplier.provider.supplier_address'] = new \PrestaShop\PrestaShop\Adapter\Supplier\SupplierAddressProvider();
