<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.profile.command_handler.edit_profile_handler' shared service.

return $this->services['prestashop.adapter.profile.command_handler.edit_profile_handler'] = new \PrestaShop\PrestaShop\Adapter\Profile\CommandHandler\EditProfileHandler();
