<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.order.invoices.by_date.data_provider' shared service.

return $this->services['prestashop.admin.order.invoices.by_date.data_provider'] = new \PrestaShopBundle\Form\Admin\Sell\Order\Invoices\InvoicesByDateDataProvider(${($_ = isset($this->services['prestashop.adapter.data_provider.order_invoice']) ? $this->services['prestashop.adapter.data_provider.order_invoice'] : ($this->services['prestashop.adapter.data_provider.order_invoice'] = new \PrestaShop\PrestaShop\Adapter\Invoice\OrderInvoiceDataProvider())) && false ?: '_'});
