<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.supplier.supplier_order_validator' shared service.

return $this->services['prestashop.adapter.supplier.supplier_order_validator'] = new \PrestaShop\PrestaShop\Adapter\Supplier\SupplierOrderValidator();
