<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.sql_manager.query_handler.get_request_sql_for_editing' shared service.

return $this->services['prestashop.adapter.sql_manager.query_handler.get_request_sql_for_editing'] = new \PrestaShop\PrestaShop\Adapter\SqlManager\QueryHandler\GetSqlRequestForEditingHandler();
