<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.employee.query_handler.get_employee_for_editing' shared service.

return $this->services['prestashop.adapter.employee.query_handler.get_employee_for_editing'] = new \PrestaShop\PrestaShop\Adapter\Profile\Employee\QueryHandler\GetEmployeeForEditingHandler();
