<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.identifiable_object.data_handler.customer_form_data_handler' shared service.

return $this->services['prestashop.core.form.identifiable_object.data_handler.customer_form_data_handler'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataHandler\CustomerFormDataHandler(${($_ = isset($this->services['prestashop.core.command_bus']) ? $this->services['prestashop.core.command_bus'] : $this->load('getPrestashop_Core_CommandBusService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->shop->id, ${($_ = isset($this->services['prestashop.core.b2b.b2b_feature']) ? $this->services['prestashop.core.b2b.b2b_feature'] : $this->load('getPrestashop_Core_B2b_B2bFeatureService.php')) && false ?: '_'}->isActive());
