<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.cms_page.query_handler.get_cms_page_category_for_editing' shared service.

return $this->services['prestashop.adapter.cms_page.query_handler.get_cms_page_category_for_editing'] = new \PrestaShop\PrestaShop\Adapter\CMS\PageCategory\QueryHandler\GetCmsPageCategoryForEditingHandler();
