<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.team.employee.configuration.employee_options_configuration' shared service.

return $this->services['prestashop.core.team.employee.configuration.employee_options_configuration'] = new \PrestaShop\PrestaShop\Core\Team\Employee\Configuration\EmployeeOptionsConfiguration(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.team.employee.configuration.options_checker']) ? $this->services['prestashop.core.team.employee.configuration.options_checker'] : $this->load('getPrestashop_Core_Team_Employee_Configuration_OptionsCheckerService.php')) && false ?: '_'});
