<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.customer.query_handler.search_customers' shared service.

return $this->services['prestashop.adapter.customer.query_handler.search_customers'] = new \PrestaShop\PrestaShop\Adapter\Customer\QueryHandler\SearchCustomersHandler();
