<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.data.factory.manufacturer_address_decorator' shared service.

return $this->services['prestashop.core.grid.data.factory.manufacturer_address_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\ManufacturerAddressGridDataFactory(${($_ = isset($this->services['prestashop.core.grid.data.factory.manufacturer_address']) ? $this->services['prestashop.core.grid.data.factory.manufacturer_address'] : $this->load('getPrestashop_Core_Grid_Data_Factory_ManufacturerAddressService.php')) && false ?: '_'});
