<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.request_sql.form_handler' shared service.

return $this->services['prestashop.admin.request_sql.form_handler'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\RequestSql\SqlRequestFormHandler(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.sql_manager.request_sql_form_data_validator']) ? $this->services['prestashop.adapter.sql_manager.request_sql_form_data_validator'] : $this->load('getPrestashop_Adapter_SqlManager_RequestSqlFormDataValidatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.bundle.form.admin.configure.advanced_parameters.request_sql.form_data_provider']) ? $this->services['prestashop.bundle.form.admin.configure.advanced_parameters.request_sql.form_data_provider'] : $this->load('getPrestashop_Bundle_Form_Admin_Configure_AdvancedParameters_RequestSql_FormDataProviderService.php')) && false ?: '_'});
