<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.legacy_file_loader' shared service.

return $this->services['prestashop.translation.legacy_file_loader'] = new \PrestaShopBundle\Translation\Loader\LegacyFileLoader(${($_ = isset($this->services['prestashop.translation.legacy_file_reader']) ? $this->services['prestashop.translation.legacy_file_reader'] : $this->load('getPrestashop_Translation_LegacyFileReaderService.php')) && false ?: '_'});
