<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.kpi_row.presenter' shared service.

return $this->services['prestashop.core.kpi_row.presenter'] = new \PrestaShop\PrestaShop\Core\Kpi\Row\KpiRowPresenter();
