<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.import.normalizer.csv_value_separator' shared service.

return $this->services['prestashop.core.import.normalizer.csv_value_separator'] = new \PrestaShop\PrestaShop\Core\Import\CsvValueSeparatorNormalizer();
