<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.currency.command_handler.update_exchange_rates' shared service.

return $this->services['prestashop.adapter.currency.command_handler.update_exchange_rates'] = new \PrestaShop\PrestaShop\Adapter\Currency\CommandHandler\RefreshExchangeRatesHandler();
