<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.meta.set_up_urls.configuration' shared service.

return $this->services['prestashop.adapter.meta.set_up_urls.configuration'] = new \PrestaShop\PrestaShop\Adapter\Meta\SetUpUrlsDataConfiguration(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.file.htaccess_file_generator']) ? $this->services['prestashop.adapter.file.htaccess_file_generator'] : $this->load('getPrestashop_Adapter_File_HtaccessFileGeneratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});
