<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.import.fields_provider.category' shared service.

return $this->services['prestashop.core.import.fields_provider.category'] = new \PrestaShop\PrestaShop\Core\Import\EntityField\Provider\CategoryFieldsProvider(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});
