<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.admin.url_generator_factory' shared service.

return $this->services['prestashop.core.admin.url_generator_factory'] = new \PrestaShopBundle\Service\TransitionalBehavior\AdminUrlGeneratorFactory(${($_ = isset($this->services['prestashop.router']) ? $this->services['prestashop.router'] : $this->load('getPrestashop_RouterService.php')) && false ?: '_'});
