<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.mail_theme.configuration' shared service.

return $this->services['prestashop.core.mail_theme.configuration'] = new \PrestaShop\PrestaShop\Core\MailTemplate\MailThemeConfiguration(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.mail_template.theme_folder_catalog']) ? $this->services['prestashop.core.mail_template.theme_folder_catalog'] : $this->load('getPrestashop_Core_MailTemplate_ThemeFolderCatalogService.php')) && false ?: '_'});
