<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.translation_route_finder' shared service.

return $this->services['prestashop.adapter.translation_route_finder'] = new \PrestaShop\PrestaShop\Adapter\Translations\TranslationRouteFinder(${($_ = isset($this->services['prestashop.service.translation']) ? $this->services['prestashop.service.translation'] : $this->load('getPrestashop_Service_TranslationService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->link, ${($_ = isset($this->services['prestashop.core.admin.module.repository']) ? $this->services['prestashop.core.admin.module.repository'] : $this->getPrestashop_Core_Admin_Module_RepositoryService()) && false ?: '_'});
