<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.search.builder.request' shared service.

return $this->services['prestashop.core.search.builder.request'] = new \PrestaShop\PrestaShop\Core\Search\Builder\RequestFiltersBuilder();
