<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.position.doctrine_grid_position_updater' shared service.

return $this->services['prestashop.core.grid.position.doctrine_grid_position_updater'] = new \PrestaShop\PrestaShop\Core\Grid\Position\GridPositionUpdater(${($_ = isset($this->services['prestashop.core.grid.position.update_handler.doctrine_position_update_handler']) ? $this->services['prestashop.core.grid.position.update_handler.doctrine_position_update_handler'] : $this->load('getPrestashop_Core_Grid_Position_UpdateHandler_DoctrinePositionUpdateHandlerService.php')) && false ?: '_'});
