<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.search_parameters.resolver' shared service.

return $this->services['prestashop.search_parameters.resolver'] = new \PrestaShopBundle\Controller\ArgumentResolver\SearchParametersResolver(${($_ = isset($this->services['prestashop.core.admin.search_parameters']) ? $this->services['prestashop.core.admin.search_parameters'] : $this->load('getPrestashop_Core_Admin_SearchParametersService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.admin.admin_filter.repository']) ? $this->services['prestashop.core.admin.admin_filter.repository'] : $this->load('getPrestashop_Core_Admin_AdminFilter_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->shop->id);
