<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.kpi_row.factory.categories' shared service.

return $this->services['prestashop.core.kpi_row.factory.categories'] = new \PrestaShop\PrestaShop\Core\Kpi\Row\HookableKpiRowFactory([0 => ${($_ = isset($this->services['prestashop.adapter.kpi.disabled_categories']) ? $this->services['prestashop.adapter.kpi.disabled_categories'] : $this->load('getPrestashop_Adapter_Kpi_DisabledCategoriesService.php')) && false ?: '_'}, 1 => ${($_ = isset($this->services['prestashop.adapter.kpi.empty_categories']) ? $this->services['prestashop.adapter.kpi.empty_categories'] : $this->load('getPrestashop_Adapter_Kpi_EmptyCategoriesService.php')) && false ?: '_'}, 2 => ${($_ = isset($this->services['prestashop.adapter.kpi.top_category']) ? $this->services['prestashop.adapter.kpi.top_category'] : $this->load('getPrestashop_Adapter_Kpi_TopCategoryService.php')) && false ?: '_'}, 3 => ${($_ = isset($this->services['prestashop.adapter.kpi.average_products_in_category']) ? $this->services['prestashop.adapter.kpi.average_products_in_category'] : $this->load('getPrestashop_Adapter_Kpi_AverageProductsInCategoryService.php')) && false ?: '_'}], ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'}, 'categories');
