<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.data.factory.manufacturer_decorator' shared service.

return $this->services['prestashop.core.grid.data.factory.manufacturer_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\ManufacturerGridDataFactory(${($_ = isset($this->services['prestashop.core.grid.data.factory.manufacturer']) ? $this->services['prestashop.core.grid.data.factory.manufacturer'] : $this->load('getPrestashop_Core_Grid_Data_Factory_ManufacturerService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.manufacturer.manufacturer_logo_thumbnail_provider']) ? $this->services['prestashop.adapter.manufacturer.manufacturer_logo_thumbnail_provider'] : $this->load('getPrestashop_Adapter_Manufacturer_ManufacturerLogoThumbnailProviderService.php')) && false ?: '_'});
