<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.webservice.form_data_provider' shared service.

return $this->services['prestashop.admin.webservice.form_data_provider'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Webservice\WebserviceFormDataProvider(${($_ = isset($this->services['prestashop.adapter.webservice.configuration']) ? $this->services['prestashop.adapter.webservice.configuration'] : $this->load('getPrestashop_Adapter_Webservice_ConfigurationService.php')) && false ?: '_'});
