<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.address.query_handler.get_manufacturer_address_for_editing_handler' shared service.

return $this->services['prestashop.adapter.address.query_handler.get_manufacturer_address_for_editing_handler'] = new \PrestaShop\PrestaShop\Adapter\Address\QueryHandler\GetManufacturerAddressForEditingHandler();
