<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.showcase_card.configuration_map' shared service.

return $this->services['prestashop.core.showcase_card.configuration_map'] = new \PrestaShop\PrestaShop\Core\Domain\ShowcaseCard\ConfigurationMap();
