<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.form.choice_provider.shop_tree_choice_provider' shared service.

return $this->services['prestashop.adapter.form.choice_provider.shop_tree_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ShopTreeChoiceProvider();
