<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.manufacturer.command_handler.bulk_toggle_manufacturer_status_handler' shared service.

return $this->services['prestashop.adapter.manufacturer.command_handler.bulk_toggle_manufacturer_status_handler'] = new \PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\BulkToggleManufacturerStatusHandler();
