<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bundle.event_listener.module_guard_listener' shared service.

return $this->services['prestashop.bundle.event_listener.module_guard_listener'] = new \PrestaShopBundle\EventListener\ModuleGuardListener(${($_ = isset($this->services['prestashop.core.security.folder_guard.vendor']) ? $this->services['prestashop.core.security.folder_guard.vendor'] : ($this->services['prestashop.core.security.folder_guard.vendor'] = new \PrestaShop\PrestaShop\Core\Security\HtaccessFolderGuard(($this->targetDirs[3].'/app/Resources/security/.htaccess.dist')))) && false ?: '_'}, ($this->targetDirs[3].'/app/../modules'), ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
