<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.employee.profile_access_checker' shared service.

return $this->services['prestashop.core.employee.profile_access_checker'] = new \PrestaShop\PrestaShop\Core\Employee\Access\ProfileAccessChecker(${($_ = isset($this->services['prestashop.adapter.employee.data_provider']) ? $this->services['prestashop.adapter.employee.data_provider'] : ($this->services['prestashop.adapter.employee.data_provider'] = new \PrestaShop\PrestaShop\Adapter\Employee\EmployeeDataProvider())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}->getInt("_PS_ADMIN_PROFILE_"));
