<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.language.language_default_fonts_catalog' shared service.

return $this->services['prestashop.core.language.language_default_fonts_catalog'] = new \PrestaShop\PrestaShop\Core\Language\LanguageDefaultFontsCatalog(['fa' => 'Tahoma', 'ar' => 'Tahoma']);
