<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.language.activator' shared service.

return $this->services['prestashop.adapter.language.activator'] = new \PrestaShop\PrestaShop\Adapter\Language\LanguageActivator();
