<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.carrier_by_reference_id' shared service.

return $this->services['prestashop.core.form.choice_provider.carrier_by_reference_id'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\CarrierByReferenceChoiceProvider(${($_ = isset($this->services['prestashop.adapter.data_provider.carrier']) ? $this->services['prestashop.adapter.data_provider.carrier'] : $this->load('getPrestashop_Adapter_DataProvider_CarrierService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguage()->id);
