<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.form.choice_provider.manufacturer_name_by_id' shared service.

return $this->services['prestashop.adapter.form.choice_provider.manufacturer_name_by_id'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\ManufacturerNameByIdChoiceProvider(${($_ = isset($this->services['prestashop.adapter.data_provider.manufacturer']) ? $this->services['prestashop.adapter.data_provider.manufacturer'] : ($this->services['prestashop.adapter.data_provider.manufacturer'] = new \PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerDataProvider())) && false ?: '_'}->getManufacturers());
