<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.category.command_handler.add_category_handler' shared service.

return $this->services['prestashop.adapter.category.command_handler.add_category_handler'] = new \PrestaShop\PrestaShop\Adapter\Category\CommandHandler\AddCategoryHandler();
