<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.link_block.grid.position_definition' shared service.

return $this->services['prestashop.module.link_block.grid.position_definition'] = new \PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition('link_block', 'id_link_block', 'position', 'id_hook');
