<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.localozation.pack.factory.localization_pack' shared service.

return $this->services['prestashop.core.localozation.pack.factory.localization_pack'] = new \PrestaShop\PrestaShop\Core\Localization\Pack\Factory\LocalizationPackFactory();
