<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.product_preferences.data_provider' shared service.

return $this->services['prestashop.admin.product_preferences.data_provider'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\ProductPreferences\ProductPreferencesFormDataProvider(${($_ = isset($this->services['prestashop.adapter.product_general.configuration']) ? $this->services['prestashop.adapter.product_general.configuration'] : $this->load('getPrestashop_Adapter_ProductGeneral_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product_pagination.configuration']) ? $this->services['prestashop.adapter.product_pagination.configuration'] : $this->load('getPrestashop_Adapter_ProductPagination_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product_page.configuration']) ? $this->services['prestashop.adapter.product_page.configuration'] : $this->load('getPrestashop_Adapter_ProductPage_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product_stock.configuration']) ? $this->services['prestashop.adapter.product_stock.configuration'] : $this->load('getPrestashop_Adapter_ProductStock_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});
