<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.tax.ecotax.ecotax_resetter' shared service.

return $this->services['prestashop.adapter.tax.ecotax.ecotax_resetter'] = new \PrestaShop\PrestaShop\Adapter\Tax\Ecotax\ProductEcotaxResetter();
