<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.localization.configuration' shared service.

return $this->services['prestashop.adapter.localization.configuration'] = new \PrestaShop\PrestaShop\Adapter\Localization\LocalizationConfiguration(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.language.activator']) ? $this->services['prestashop.adapter.language.activator'] : ($this->services['prestashop.adapter.language.activator'] = new \PrestaShop\PrestaShop\Adapter\Language\LanguageActivator())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.manager.currency']) ? $this->services['prestashop.adapter.manager.currency'] : ($this->services['prestashop.adapter.manager.currency'] = new \PrestaShop\PrestaShop\Adapter\Currency\CurrencyManager())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.admin.data_provider.module_interface']) ? $this->services['prestashop.core.admin.data_provider.module_interface'] : $this->getPrestashop_Core_Admin_DataProvider_ModuleInterfaceService()) && false ?: '_'});
