<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.translation.chainextractor' shared service.

$this->services['prestashop.translation.chainextractor'] = $instance = new \PrestaShop\TranslationToolsBundle\Translation\Extractor\ChainExtractor();

$instance->addExtractor('php', ${($_ = isset($this->services['prestashop.translation.extractor.php']) ? $this->services['prestashop.translation.extractor.php'] : ($this->services['prestashop.translation.extractor.php'] = new \PrestaShop\TranslationToolsBundle\Translation\Extractor\PhpExtractor())) && false ?: '_'});
$instance->addExtractor('twig', ${($_ = isset($this->services['prestashop.translation.extractor.twig']) ? $this->services['prestashop.translation.extractor.twig'] : $this->load('getPrestashop_Translation_Extractor_TwigService.php')) && false ?: '_'});
$instance->addExtractor('smarty', ${($_ = isset($this->services['prestashop.translation.extractor.smarty']) ? $this->services['prestashop.translation.extractor.smarty'] : $this->load('getPrestashop_Translation_Extractor_SmartyService.php')) && false ?: '_'});

return $instance;
