<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.language.command_handler.toggle_language_status_handler' shared service.

return $this->services['prestashop.adapter.language.command_handler.toggle_language_status_handler'] = new \PrestaShop\PrestaShop\Adapter\Language\CommandHandler\ToggleLanguageStatusHandler();
