<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.api.supplier.controller' shared service.

$this->services['prestashop.core.api.supplier.controller'] = $instance = new \PrestaShopBundle\Controller\Api\SupplierController();

$instance->supplierRepository = ${($_ = isset($this->services['prestashop.core.api.supplier.repository']) ? $this->services['prestashop.core.api.supplier.repository'] : $this->load('getPrestashop_Core_Api_Supplier_RepositoryService.php')) && false ?: '_'};
$instance->setLogger(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
$instance->setContainer($this);

return $instance;
