<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.backup.comparator.backup_by_date_comparator' shared service.

return $this->services['prestashop.core.backup.comparator.backup_by_date_comparator'] = new \PrestaShop\PrestaShop\Core\Backup\Comparator\BackupByDateComparator();
