<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.mail_template.transformation.css_inline' shared service.

return $this->services['prestashop.core.mail_template.transformation.css_inline'] = new \PrestaShop\PrestaShop\Core\MailTemplate\Transformation\CSSInlineTransformation();
