<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.debug_mode' shared service.

return $this->services['prestashop.adapter.debug_mode'] = new \PrestaShop\PrestaShop\Adapter\Debug\DebugMode();
