<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.language.query_handler.get_language_for_editing' shared service.

return $this->services['prestashop.adapter.language.query_handler.get_language_for_editing'] = new \PrestaShop\PrestaShop\Adapter\Language\QueryHandler\GetLanguageForEditingHandler();
