<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.import.config_factory' shared service.

return $this->services['prestashop.core.import.config_factory'] = new \PrestaShop\PrestaShop\Core\Import\Configuration\ImportConfigFactory();
