<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.invoice_model_by_name' shared service.

return $this->services['prestashop.core.form.choice_provider.invoice_model_by_name'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\InvoiceModelByNameChoiceProvider(${($_ = isset($this->services['prestashop.core.file.cached_finder.invoice_model']) ? $this->services['prestashop.core.file.cached_finder.invoice_model'] : $this->load('getPrestashop_Core_File_CachedFinder_InvoiceModelService.php')) && false ?: '_'});
