<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.file.robots_text_file_generator' shared service.

return $this->services['prestashop.adapter.file.robots_text_file_generator'] = new \PrestaShop\PrestaShop\Adapter\File\RobotsTextFileGenerator();
