<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.filter_categories_request_purifier' shared service.

return $this->services['prestashop.adapter.product.filter_categories_request_purifier'] = new \PrestaShop\PrestaShop\Adapter\Product\FilterCategoriesRequestPurifier();
