<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.import.file_opener' shared service.

return $this->services['prestashop.adapter.import.file_opener'] = new \PrestaShop\PrestaShop\Adapter\Import\CsvFileOpener(${($_ = isset($this->services['prestashop.adapter.import.excel_to_csv_converter']) ? $this->services['prestashop.adapter.import.excel_to_csv_converter'] : $this->load('getPrestashop_Adapter_Import_ExcelToCsvConverterService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.import.dir']) ? $this->services['prestashop.core.import.dir'] : $this->load('getPrestashop_Core_Import_DirService.php')) && false ?: '_'});
