<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.import.file_uploader' shared service.

return $this->services['prestashop.core.import.file_uploader'] = new \PrestaShop\PrestaShop\Core\Import\File\FileUploader(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.import.dir']) ? $this->services['prestashop.core.import.dir'] : $this->load('getPrestashop_Core_Import_DirService.php')) && false ?: '_'});
