<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.cms_page.data_provider.cms_page_view' shared service.

return $this->services['prestashop.core.cms_page.data_provider.cms_page_view'] = new \PrestaShop\PrestaShop\Core\CMS\CmsPageViewDataProvider(${($_ = isset($this->services['prestashop.core.query_bus']) ? $this->services['prestashop.core.query_bus'] : $this->load('getPrestashop_Core_QueryBusService.php')) && false ?: '_'});
