<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.webservice.command_handler.add_webservice_key_handler' shared service.

return $this->services['prestashop.adapter.webservice.command_handler.add_webservice_key_handler'] = new \PrestaShop\PrestaShop\Adapter\Webservice\CommandHandler\AddWebserviceKeyHandler();
