<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.command_bus' shared service.

return $this->services['prestashop.core.command_bus'] = new \PrestaShop\PrestaShop\Core\CommandBus\TacticianCommandBusAdapter(${($_ = isset($this->services['tactician.commandbus.default']) ? $this->services['tactician.commandbus.default'] : $this->load('getTactician_Commandbus_DefaultService.php')) && false ?: '_'});
