<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.accessible_tab' shared service.

return $this->services['prestashop.core.form.choice_provider.accessible_tab'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\TabChoiceProvider(${($_ = isset($this->services['prestashop.adapter.data_provider.tab']) ? $this->services['prestashop.adapter.data_provider.tab'] : $this->load('getPrestashop_Adapter_DataProvider_TabService.php')) && false ?: '_'}->getViewableTabsForContextEmployee(${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguage()->id));
