<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.module.data_provider.tab_module_list' shared service.

return $this->services['prestashop.adapter.module.data_provider.tab_module_list'] = new \PrestaShop\PrestaShop\Adapter\Module\TabModuleListProvider();
