<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.import.data_row.presenter' shared service.

return $this->services['prestashop.core.import.data_row.presenter'] = new \PrestaShop\PrestaShop\Core\Import\File\DataRow\DataRowPresenter();
