<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.mail_template.generator' shared service.

return $this->services['prestashop.core.mail_template.generator'] = new \PrestaShop\PrestaShop\Core\MailTemplate\MailTemplateGenerator(${($_ = isset($this->services['prestashop.adapter.mail_template.twig_renderer']) ? $this->services['prestashop.adapter.mail_template.twig_renderer'] : $this->load('getPrestashop_Adapter_MailTemplate_TwigRendererService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
