<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bundle.form.data_transformer.default_language_to_filled_array' shared service.

return $this->services['prestashop.bundle.form.data_transformer.default_language_to_filled_array'] = new \PrestaShopBundle\Form\DataTransformer\DefaultLanguageToFilledArrayDataTransformer(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}->get("PS_LANG_DEFAULT"));
