<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.tax.query_handler.get_tax_for_editing_handler' shared service.

return $this->services['prestashop.adapter.tax.query_handler.get_tax_for_editing_handler'] = new \PrestaShop\PrestaShop\Adapter\Tax\QueryHandler\GetTaxForEditingHandler();
