<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.cms_page.command_handler.toggle_cms_page_status' shared service.

return $this->services['prestashop.adapter.cms_page.command_handler.toggle_cms_page_status'] = new \PrestaShop\PrestaShop\Adapter\CMS\Page\CommandHandler\ToggleCmsPageStatusHandler();
