<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.smarty' shared service.

$this->services['prestashop.smarty'] = $instance = new \PrestaShop\TranslationToolsBundle\Smarty();

$instance->setCompileDir(($this->targetDirs[0].'/smarty'));
$instance->forceCompile(true);
$instance->registerResource('module', ${($_ = isset($this->services['prestashop.translation.helper.smarty.smarty_resource_module']) ? $this->services['prestashop.translation.helper.smarty.smarty_resource_module'] : ($this->services['prestashop.translation.helper.smarty.smarty_resource_module'] = new \PrestaShop\TranslationToolsBundle\Translation\Helper\Smarty\SmartyResourceModule())) && false ?: '_'});
$instance->registerResource('parent', ${($_ = isset($this->services['prestashop.translation.helper.smarty.smarty_resource_parent']) ? $this->services['prestashop.translation.helper.smarty.smarty_resource_parent'] : ($this->services['prestashop.translation.helper.smarty.smarty_resource_parent'] = new \PrestaShop\TranslationToolsBundle\Translation\Helper\Smarty\SmartyResourceParent())) && false ?: '_'});

return $instance;
