<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.permissions_choice_provider' shared service.

return $this->services['prestashop.core.form.choice_provider.permissions_choice_provider'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\PermissionsChoiceProvider(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'});
