<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.order_state_by_id' shared service.

return $this->services['prestashop.core.form.choice_provider.order_state_by_id'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\OrderStateByIdChoiceProvider(${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguage()->id, ${($_ = isset($this->services['prestashop.adapter.data_provider.order_state']) ? $this->services['prestashop.adapter.data_provider.order_state'] : ($this->services['prestashop.adapter.data_provider.order_state'] = new \PrestaShop\PrestaShop\Adapter\OrderState\OrderStateDataProvider())) && false ?: '_'});
