<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.identifiable_object.data_provider.contact_form_data_provider' shared service.

return $this->services['prestashop.core.form.identifiable_object.data_provider.contact_form_data_provider'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\ContactFormDataProvider(${($_ = isset($this->services['prestashop.core.query_bus']) ? $this->services['prestashop.core.query_bus'] : $this->load('getPrestashop_Core_QueryBusService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.bundle.form.data_transformer.string_array_to_integer_array']) ? $this->services['prestashop.bundle.form.data_transformer.string_array_to_integer_array'] : ($this->services['prestashop.bundle.form.data_transformer.string_array_to_integer_array'] = new \PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.shop.context']) ? $this->services['prestashop.adapter.shop.context'] : ($this->services['prestashop.adapter.shop.context'] = new \PrestaShop\PrestaShop\Adapter\Shop\Context())) && false ?: '_'}->getContextListShopID());
