<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.currency.query_handler.get_currency_for_editing' shared service.

return $this->services['prestashop.adapter.currency.query_handler.get_currency_for_editing'] = new \PrestaShop\PrestaShop\Adapter\Currency\QueryHandler\GetCurrencyForEditingHandler(${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->shop->id);
