<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.tax.command_handler.bulk_toggle_tax_status_handler' shared service.

return $this->services['prestashop.adapter.tax.command_handler.bulk_toggle_tax_status_handler'] = new \PrestaShop\PrestaShop\Adapter\Tax\CommandHandler\BulkToggleTaxStatusHandler();
