<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.cms_page_category.position_definition' shared service.

return $this->services['prestashop.core.grid.cms_page_category.position_definition'] = new \PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition('cms_category', 'id_cms_category', 'position', 'id_parent');
