<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.sql_loader' shared service.

return $this->services['prestashop.translation.sql_loader'] = new \PrestaShopBundle\Translation\Loader\SqlTranslationLoader();
