<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.image.file_deleter' shared service.

return $this->services['prestashop.core.image.file_deleter'] = new \PrestaShop\PrestaShop\Core\Image\Deleter\ImageFileDeleter();
