<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.kpi_row.factory.customers' shared service.

return $this->services['prestashop.core.kpi_row.factory.customers'] = new \PrestaShop\PrestaShop\Core\Kpi\Row\HookableKpiRowFactory([0 => ${($_ = isset($this->services['prestashop.adapter.kpi.most_common_customers_gender']) ? $this->services['prestashop.adapter.kpi.most_common_customers_gender'] : $this->load('getPrestashop_Adapter_Kpi_MostCommonCustomersGenderService.php')) && false ?: '_'}, 1 => ${($_ = isset($this->services['prestashop.adapter.kpi.average_customer_age']) ? $this->services['prestashop.adapter.kpi.average_customer_age'] : $this->load('getPrestashop_Adapter_Kpi_AverageCustomerAgeService.php')) && false ?: '_'}, 2 => ${($_ = isset($this->services['prestashop.adapter.kpi.order_per_customer']) ? $this->services['prestashop.adapter.kpi.order_per_customer'] : $this->load('getPrestashop_Adapter_Kpi_OrderPerCustomerService.php')) && false ?: '_'}, 3 => ${($_ = isset($this->services['prestashop.adapter.kpi.newsletter_registrations']) ? $this->services['prestashop.adapter.kpi.newsletter_registrations'] : $this->load('getPrestashop_Adapter_Kpi_NewsletterRegistrationsService.php')) && false ?: '_'}], ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'}, 'customers');
