<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.factory.customer' shared service.

return $this->services['prestashop.core.grid.factory.customer'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(${($_ = isset($this->services['prestashop.core.grid.definition.factory.customer']) ? $this->services['prestashop.core.grid.definition.factory.customer'] : $this->load('getPrestashop_Core_Grid_Definition_Factory_CustomerService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.grid.data_provider.customer_decorator']) ? $this->services['prestashop.core.grid.data_provider.customer_decorator'] : $this->load('getPrestashop_Core_Grid_DataProvider_CustomerDecoratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.grid.filter.form_factory']) ? $this->services['prestashop.core.grid.filter.form_factory'] : $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'});
