<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.factory.supplier_decorator' shared service.

return $this->services['prestashop.core.grid.factory.supplier_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\SupplierGridDataFactory(${($_ = isset($this->services['prestashop.core.grid.data_provider.supplier']) ? $this->services['prestashop.core.grid.data_provider.supplier'] : $this->load('getPrestashop_Core_Grid_DataProvider_SupplierService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.supplier.provider.supplier_logo']) ? $this->services['prestashop.adapter.supplier.provider.supplier_logo'] : $this->load('getPrestashop_Adapter_Supplier_Provider_SupplierLogoService.php')) && false ?: '_'});
