<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.mailing_information' shared service.

return $this->services['prestashop.adapter.mailing_information'] = new \PrestaShop\PrestaShop\Adapter\Mail\MailingInformation();
