<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.filters_builder.resolver' shared service.

return $this->services['prestashop.filters_builder.resolver'] = new \PrestaShopBundle\Controller\ArgumentResolver\FiltersBuilderResolver(${($_ = isset($this->services['prestashop.core.search.builder']) ? $this->services['prestashop.core.search.builder'] : $this->load('getPrestashop_Core_Search_BuilderService.php')) && false ?: '_'});
