<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.meta.url_schema.configuration' shared service.

return $this->services['prestashop.adapter.meta.url_schema.configuration'] = new \PrestaShop\PrestaShop\Adapter\Meta\UrlSchemaDataConfiguration(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.data_provider.default_route']) ? $this->services['prestashop.adapter.data_provider.default_route'] : ($this->services['prestashop.adapter.data_provider.default_route'] = new \PrestaShop\PrestaShop\Adapter\Routes\DefaultRouteProvider())) && false ?: '_'}->getRules());
