<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.domain.theme.command_handler.adapt_theme_to_rtl_languages_handler' shared service.

return $this->services['prestashop.core.domain.theme.command_handler.adapt_theme_to_rtl_languages_handler'] = new \PrestaShop\PrestaShop\Core\Domain\Theme\CommandHandler\AdaptThemeToRTLLanguagesHandler(${($_ = isset($this->services['prestashop.core.localization.rtl.processor_factory']) ? $this->services['prestashop.core.localization.rtl.processor_factory'] : $this->load('getPrestashop_Core_Localization_Rtl_ProcessorFactoryService.php')) && false ?: '_'});
