<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.data_provider.default_route' shared service.

return $this->services['prestashop.adapter.data_provider.default_route'] = new \PrestaShop\PrestaShop\Adapter\Routes\DefaultRouteProvider();
