<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.localization.form_data_provider' shared service.

return $this->services['prestashop.admin.localization.form_data_provider'] = new \PrestaShopBundle\Form\Admin\Improve\International\Localization\LocalizationFormDataProvider(${($_ = isset($this->services['prestashop.adapter.localization.configuration']) ? $this->services['prestashop.adapter.localization.configuration'] : $this->load('getPrestashop_Adapter_Localization_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.local_units.configuration']) ? $this->services['prestashop.adapter.local_units.configuration'] : $this->load('getPrestashop_Adapter_LocalUnits_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.localization_advanced.configuration']) ? $this->services['prestashop.adapter.localization_advanced.configuration'] : $this->load('getPrestashop_Adapter_LocalizationAdvanced_ConfigurationService.php')) && false ?: '_'});
