<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.webservice.server_requirements_checker' shared service.

return $this->services['prestashop.core.webservice.server_requirements_checker'] = new \PrestaShop\PrestaShop\Core\Webservice\ServerRequirementsChecker(${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.hosting_information']) ? $this->services['prestashop.adapter.hosting_information'] : ($this->services['prestashop.adapter.hosting_information'] = new \PrestaShop\PrestaShop\Adapter\Hosting\HostingInformation())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.configuration.php_extension_checker']) ? $this->services['prestashop.core.configuration.php_extension_checker'] : ($this->services['prestashop.core.configuration.php_extension_checker'] = new \PrestaShop\PrestaShop\Core\Configuration\PhpExtensionChecker())) && false ?: '_'});
