<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.api.stock.controller' shared service.

$this->services['prestashop.core.api.stock.controller'] = $instance = new \PrestaShopBundle\Controller\Api\StockController();

$instance->movements = ${($_ = isset($this->services['prestashop.core.api.stock.movements_collection']) ? $this->services['prestashop.core.api.stock.movements_collection'] : ($this->services['prestashop.core.api.stock.movements_collection'] = new \PrestaShopBundle\Api\Stock\MovementsCollection())) && false ?: '_'};
$instance->stockRepository = ${($_ = isset($this->services['prestashop.core.api.stock.repository']) ? $this->services['prestashop.core.api.stock.repository'] : $this->load('getPrestashop_Core_Api_Stock_RepositoryService.php')) && false ?: '_'};
$instance->queryParams = ${($_ = isset($this->services['prestashop.core.api.query_stock_params_collection']) ? $this->services['prestashop.core.api.query_stock_params_collection'] : ($this->services['prestashop.core.api.query_stock_params_collection'] = new \PrestaShopBundle\Api\QueryStockParamsCollection())) && false ?: '_'};
$instance->setLogger(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
$instance->setContainer($this);

return $instance;
