<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.link_block.form_handler' shared service.

return $this->services['prestashop.module.link_block.form_handler'] = new \PrestaShop\PrestaShop\Core\Form\FormHandler(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}->createBuilder(), ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.module.link_block.form_provider']) ? $this->services['prestashop.module.link_block.form_provider'] : $this->load('getPrestashop_Module_LinkBlock_FormProviderService.php')) && false ?: '_'}, ['link_block' => 'PrestaShop\\Module\\LinkList\\Form\\Type\\LinkBlockType'], 'AdminLinkWidget');
