<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.foundation.version' shared service.

return $this->services['prestashop.core.foundation.version'] = new \PrestaShop\PrestaShop\Core\Foundation\Version('1.7.6.8', '1.7', 17, 6, 8);
