<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.translation.helper.smarty.smarty_resource_parent' shared service.

return $this->services['prestashop.translation.helper.smarty.smarty_resource_parent'] = new \PrestaShop\TranslationToolsBundle\Translation\Helper\Smarty\SmartyResourceParent();
