<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.maintenance.form_provider' shared service.

return $this->services['prestashop.adapter.maintenance.form_provider'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\General\MaintenanceFormDataProvider(${($_ = isset($this->services['prestashop.adapter.maintenance.configuration']) ? $this->services['prestashop.adapter.maintenance.configuration'] : $this->load('getPrestashop_Adapter_Maintenance_ConfigurationService.php')) && false ?: '_'});
