<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.identifiable_object.data_provider.customer_form_data_provider' shared service.

return $this->services['prestashop.core.form.identifiable_object.data_provider.customer_form_data_provider'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\CustomerFormDataProvider(${($_ = isset($this->services['prestashop.core.query_bus']) ? $this->services['prestashop.core.query_bus'] : $this->load('getPrestashop_Core_QueryBusService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.group.provider.default_groups_provider']) ? $this->services['prestashop.adapter.group.provider.default_groups_provider'] : $this->load('getPrestashop_Adapter_Group_Provider_DefaultGroupsProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.b2b.b2b_feature']) ? $this->services['prestashop.core.b2b.b2b_feature'] : $this->load('getPrestashop_Core_B2b_B2bFeatureService.php')) && false ?: '_'}->isActive());
