<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.import.handler_finder' shared service.

return $this->services['prestashop.adapter.import.handler_finder'] = new \PrestaShop\PrestaShop\Adapter\Import\Handler\ImportHandlerFinder(${($_ = isset($this->services['prestashop.adapter.import.handler.category']) ? $this->services['prestashop.adapter.import.handler.category'] : $this->load('getPrestashop_Adapter_Import_Handler_CategoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.import.handler.product']) ? $this->services['prestashop.adapter.import.handler.product'] : $this->load('getPrestashop_Adapter_Import_Handler_ProductService.php')) && false ?: '_'});
