<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.backup.backup_remover' shared service.

return $this->services['prestashop.adapter.backup.backup_remover'] = new \PrestaShop\PrestaShop\Adapter\Backup\BackupRemover();
