<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.mail_theme.form_data_provider' shared service.

return $this->services['prestashop.admin.mail_theme.form_data_provider'] = new \PrestaShopBundle\Form\Admin\Improve\Design\MailTheme\MailThemeFormDataProvider(${($_ = isset($this->services['prestashop.core.mail_theme.configuration']) ? $this->services['prestashop.core.mail_theme.configuration'] : $this->load('getPrestashop_Core_MailTheme_ConfigurationService.php')) && false ?: '_'});
