<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.search.builder.repository' shared service.

return $this->services['prestashop.core.search.builder.repository'] = new \PrestaShop\PrestaShop\Core\Search\Builder\RepositoryFiltersBuilder(${($_ = isset($this->services['prestashop.core.admin.admin_filter.repository']) ? $this->services['prestashop.core.admin.admin_filter.repository'] : $this->load('getPrestashop_Core_Admin_AdminFilter_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.data_provider.employee']) ? $this->services['prestashop.adapter.data_provider.employee'] : $this->load('getPrestashop_Adapter_DataProvider_EmployeeService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->shop->id);
