<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.module.payment_module_provider' shared service.

return $this->services['prestashop.adapter.module.payment_module_provider'] = new \PrestaShop\PrestaShop\Adapter\Module\PaymentModuleListProvider(${($_ = isset($this->services['prestashop.core.admin.module.repository']) ? $this->services['prestashop.core.admin.module.repository'] : $this->getPrestashop_Core_Admin_Module_RepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.bundle.repository.module']) ? $this->services['prestashop.bundle.repository.module'] : $this->load('getPrestashop_Bundle_Repository_ModuleService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->shop->id);
