<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.manufacturer.query_handler.get_manufacturer_for_viewing_handler' shared service.

return $this->services['prestashop.adapter.manufacturer.query_handler.get_manufacturer_for_viewing_handler'] = new \PrestaShop\PrestaShop\Adapter\Manufacturer\QueryHandler\GetManufacturerForViewingHandler();
