<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.manufacturer.command_handler.add_manufacturer_handler' shared service.

return $this->services['prestashop.adapter.manufacturer.command_handler.add_manufacturer_handler'] = new \PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\AddManufacturerHandler();
