<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.security.voter.product' shared service.

return $this->services['prestashop.security.voter.product'] = new \PrestaShopBundle\Security\Voter\PageVoter();
