<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.module.tab.eventsubscriber' shared service.

return $this->services['prestashop.adapter.module.tab.eventsubscriber'] = new \PrestaShop\PrestaShop\Adapter\Module\Tab\ModuleTabManagementSubscriber(${($_ = isset($this->services['prestashop.adapter.module.tab.register']) ? $this->services['prestashop.adapter.module.tab.register'] : $this->load('getPrestashop_Adapter_Module_Tab_RegisterService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.module.tab.unregister']) ? $this->services['prestashop.adapter.module.tab.unregister'] : $this->load('getPrestashop_Adapter_Module_Tab_UnregisterService.php')) && false ?: '_'});
