<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.choice_provider.mail_themes' shared service.

return $this->services['prestashop.core.form.choice_provider.mail_themes'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\MailThemeChoiceProvider(${($_ = isset($this->services['prestashop.core.mail_template.theme_folder_catalog']) ? $this->services['prestashop.core.mail_template.theme_folder_catalog'] : $this->load('getPrestashop_Core_MailTemplate_ThemeFolderCatalogService.php')) && false ?: '_'});
