<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.php_parameters' shared service.

return $this->services['prestashop.adapter.php_parameters'] = new \PrestaShop\PrestaShop\Adapter\Configuration\PhpParameters(($this->targetDirs[3].'/app/config/parameters.php'));
