<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.language.rtl.installed_language_checker' shared service.

return $this->services['prestashop.adapter.language.rtl.installed_language_checker'] = new \PrestaShop\PrestaShop\Adapter\Language\RTL\InstalledLanguageChecker(${($_ = isset($this->services['prestashop.adapter.data_provider.language']) ? $this->services['prestashop.adapter.data_provider.language'] : ($this->services['prestashop.adapter.data_provider.language'] = new \PrestaShop\PrestaShop\Adapter\Language\LanguageDataProvider())) && false ?: '_'});
