<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.currency.grid_data_factory' shared service.

return $this->services['prestashop.core.currency.grid_data_factory'] = new \PrestaShop\PrestaShop\Core\Currency\CurrencyGridDataFactory(${($_ = isset($this->services['prestashop.core.grid.data_provider.currency']) ? $this->services['prestashop.core.grid.data_provider.currency'] : $this->load('getPrestashop_Core_Grid_DataProvider_CurrencyService.php')) && false ?: '_'});
