<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.image.parser.image_tag_source_parser' shared service.

return $this->services['prestashop.core.image.parser.image_tag_source_parser'] = new \PrestaShop\PrestaShop\Core\Image\Parser\ImageTagSourceParser(${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getRootUrl());
