<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.import.excel_to_csv_converter' shared service.

return $this->services['prestashop.adapter.import.excel_to_csv_converter'] = new \PrestaShop\PrestaShop\Adapter\Converter\ExcelToCsvFileConverter(${($_ = isset($this->services['filesystem']) ? $this->services['filesystem'] : ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.import.dir']) ? $this->services['prestashop.core.import.dir'] : $this->load('getPrestashop_Core_Import_DirService.php')) && false ?: '_'}->getDir(), (${($_ = isset($this->services['prestashop.core.import.dir']) ? $this->services['prestashop.core.import.dir'] : $this->load('getPrestashop_Core_Import_DirService.php')) && false ?: '_'}->getDir() . "csvfromexcel/"));
