<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.import.file_removal' shared service.

return $this->services['prestashop.core.import.file_removal'] = new \PrestaShop\PrestaShop\Core\Import\File\FileRemoval(${($_ = isset($this->services['prestashop.core.import.dir']) ? $this->services['prestashop.core.import.dir'] : $this->load('getPrestashop_Core_Import_DirService.php')) && false ?: '_'});
