<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.meta.shop_url.configuration' shared service.

return $this->services['prestashop.adapter.meta.shop_url.configuration'] = new \PrestaShop\PrestaShop\Adapter\Meta\ShopUrlDataConfiguration(${($_ = isset($this->services['prestashop.adapter.shop.shop_url']) ? $this->services['prestashop.adapter.shop.shop_url'] : $this->load('getPrestashop_Adapter_Shop_ShopUrlService.php')) && false ?: '_'}->getMainShopUrl(), ${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.file.htaccess_file_generator']) ? $this->services['prestashop.adapter.file.htaccess_file_generator'] : $this->load('getPrestashop_Adapter_File_HtaccessFileGeneratorService.php')) && false ?: '_'});
