<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.factory.language_decorator' shared service.

return $this->services['prestashop.core.grid.factory.language_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\LanguageGridDataFactory(${($_ = isset($this->services['prestashop.core.grid.data.factory.language']) ? $this->services['prestashop.core.grid.data.factory.language'] : $this->load('getPrestashop_Core_Grid_Data_Factory_LanguageService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.language.language_flag_thumbnail_provider']) ? $this->services['prestashop.adapter.language.language_flag_thumbnail_provider'] : $this->load('getPrestashop_Adapter_Language_LanguageFlagThumbnailProviderService.php')) && false ?: '_'});
