<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.email.email_log_eraser' shared service.

return $this->services['prestashop.adapter.email.email_log_eraser'] = new \PrestaShop\PrestaShop\Adapter\Email\EmailLogEraser();
