<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.meta.meta_eraser' shared service.

return $this->services['prestashop.adapter.meta.meta_eraser'] = new \PrestaShop\PrestaShop\Adapter\Meta\MetaEraser();
