<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.image.uploader.manufacturer_image_uploader' shared service.

return $this->services['prestashop.adapter.image.uploader.manufacturer_image_uploader'] = new \PrestaShop\PrestaShop\Adapter\Image\Uploader\ManufacturerImageUploader();
