<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.factory.cms_page_category' shared service.

return $this->services['prestashop.core.grid.factory.cms_page_category'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(${($_ = isset($this->services['prestashop.core.grid.definition.factory.cms_page_category']) ? $this->services['prestashop.core.grid.definition.factory.cms_page_category'] : $this->load('getPrestashop_Core_Grid_Definition_Factory_CmsPageCategoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.grid.data_provider.cms_page_category']) ? $this->services['prestashop.core.grid.data_provider.cms_page_category'] : $this->load('getPrestashop_Core_Grid_DataProvider_CmsPageCategoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.grid.filter.cms_page_form_factory']) ? $this->services['prestashop.core.grid.filter.cms_page_form_factory'] : $this->load('getPrestashop_Core_Grid_Filter_CmsPageFormFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'});
