<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.grid_factory.manufacturer' shared service.

return $this->services['prestashop.core.grid.grid_factory.manufacturer'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(${($_ = isset($this->services['prestashop.core.grid.definition.factory.manufacturer']) ? $this->services['prestashop.core.grid.definition.factory.manufacturer'] : $this->load('getPrestashop_Core_Grid_Definition_Factory_ManufacturerService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.grid.data.factory.manufacturer_decorator']) ? $this->services['prestashop.core.grid.data.factory.manufacturer_decorator'] : $this->load('getPrestashop_Core_Grid_Data_Factory_ManufacturerDecoratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.grid.filter.form_factory']) ? $this->services['prestashop.core.grid.filter.form_factory'] : $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'});
