<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.manager.currency' shared service.

return $this->services['prestashop.adapter.manager.currency'] = new \PrestaShop\PrestaShop\Adapter\Currency\CurrencyManager();
