<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'swiftmailer.mailer.default.spool' shared service.

return $this->services['swiftmailer.mailer.default.spool'] = new \Swift_MemorySpool();
