<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'tactician.plugins.named_command.extractor' shared service.

return $this->services['tactician.plugins.named_command.extractor'] = new \League\Tactician\Plugins\NamedCommand\NamedCommandExtractor();
