<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'tactician.middleware.validator' shared service.

return $this->services['tactician.middleware.validator'] = new \League\Tactician\Bundle\Middleware\ValidatorMiddleware(${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'});
