<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'tactician.handler.method_name_inflector.handle_class_name' shared service.

return $this->services['tactician.handler.method_name_inflector.handle_class_name'] = new \League\Tactician\Handler\MethodNameInflector\HandleClassNameInflector();
