<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'tactician.middleware.locking' shared service.

return $this->services['tactician.middleware.locking'] = new \League\Tactician\Plugins\LockingMiddleware();
