<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'tactician.handler.command_name_extractor.class_name' shared service.

return $this->services['tactician.handler.command_name_extractor.class_name'] = new \League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor();
