#!/bin/bash
if [ -f ./var/log/mqt ]; then
  docker-compose exec --user app phpfpm mkdir -p ./var/log/mqt
fi
docker-compose exec --user app phpfpm composer coding-standard
if [ $? != 0 ]; then
  echo -e "\e[91mErrors where found. Fix them before commit\e[0m"
  sensible-browser ./webroot/var/log/mqt/full.txt
  exit $?
fi

docker-compose exec --user app phpfpm composer copy-peste-detector
if [ $? != 0 ]; then
  echo -e "\e[91mDuplicated code was found. Fix them before commit\e[0m"
  sensible-browser ./webroot/var/log/mqt/duplicated.txt
  exit $?
fi

docker-compose exec --user app phpfpm composer mess-detector
if [ $? != 0 ]; then
  echo -e "\e[91mDuplicated code was found. Fix them before commit\e[0m"
  sensible-browser ./webroot/var/log/mqt/mess.html
  exit $?
fi
