#!/bin/sh

STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
	oIFS=$IFS
	IFS='
	'
	SFILES="$1"
	IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

cd Application
echo "Checking PHP Lint..."
for FILE in $SFILES
do
  # Run inside the correct location
  docker-compose exec -T --user www-data phpfpm sh -c "php -l -d display_errors=0 ${FILE##Application\/webroot\/}"
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
	  cd ..
		exit 1
	fi
  # replace mapping for next pass of the command
	FILES="$FILES ${FILE##Application\/webroot\/}"
done

if [ "$FILES" != "" ]
then
	echo "Running Code Sniffer..."
  docker-compose exec -T --user www-data phpfpm sh -c "./dev/magento-coding-standard/vendor/bin/phpcs -n -p $FILES"
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		cd ..
		exit 1
	fi
fi
cd ..
exit $?