#!/bin/bash
docker-compose exec phpfpm su -s /bin/bash www-data -c "composer coding-standard"
if [ $? != 0 ]; then
  echo -e "\e[91mErrors where found. Fix them before commit\e[0m"
  sensible-browser ./webroot/var/log/mqt/full.txt
  exit $?
fi

docker-compose exec phpfpm su -s /bin/bash www-data -c "composer copy-peste-detector"
if [ $? != 0 ]; then
  echo -e "\e[91mDuplicated code was found. Fix them before commit\e[0m"
  sensible-browser ./webroot/var/log/mqt/duplicated.txt
  exit $?
fi

docker-compose exec phpfpm su -s /bin/bash www-data -c "composer mess-detector"
if [ $? != 0 ]; then
  echo -e "\e[91mDuplicated code was found. Fix them before commit\e[0m"
  sensible-browser ./webroot/var/log/mqt/mess.html
  exit $?
fi