#!/bin/bash
# Reference: https://wiki.bash-hackers.org/scripting/posparams
echo '
  _____            __       _______
 / ____|          / _|     |__   __|
| (___   ___ _ __| |_ ___     | | ___  __ _ _ __  ___
 \___ \ / _ \ `__|  _/ _ \    | |/ _ \/ _` | `_ `´_  \
 ____) |  __/ |  | ||  __/    | |  __/ (_| | | | | | |
|_____/ \___|_|  |_| \___|    |_|\___|\__,_|_| |_| |_|
--------------------------------------------------------
Magento Cloud command runner - By Serfe Magento Team
--------------------------------------------------------';
if [ -z $1 ]; then
  echo -e "\e[31mNothing to run!\e[0m"
  echo " Options are:";
  ls -1 ./.serfe
  exit -1;
fi

command="$1"
shift

if [ -x ./.serfe/$command ]; then
  bash ./.serfe/$command $@
 else
   echo -e "\e[31mThat command does not exists!\e[0m";
   echo " Options are:";
   ls -1 ./.serfe
   exit -2;
fi
