<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7zqacrs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7zqacrs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7zqacrs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7zqacrs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7zqacrs\appDevDebugProjectContainer([
    'container.build_hash' => '7zqacrs',
    'container.build_id' => '772146c0',
    'container.build_time' => 1606840993,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7zqacrs');
